# -*- coding: utf-8 -*-
"""Wholesale_Customers_Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zrgloYxJp1xoWDeZl1mwYTJ7rGW4kB1f
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np

from sklearn.cluster import KMeans
# Calculate silhouette_score
from sklearn.metrics import silhouette_score

import warnings
warnings.filterwarnings("ignore")

from google.colab import drive
drive.mount('/gdrive')
#Change current working directory to gdrive
# %cd /gdrive

#Read files
trainfile = r'/gdrive/My Drive/CIS 508/Assignment/HW4/Wholesale_Customers_Data.csv'
trainData = pd.read_csv(trainfile) #creates a dataframe
print(trainData.shape)

#Remove Channel and Region Column
X_train = trainData.drop(["Channel","Region"], axis=1)
# X_train = X_train.drop(["Region"], axis=1)
print(X_train.shape)

#K-Means Clustering ========================================================================
#Default Mode - K=8
kmeans = KMeans()
kmeans.fit(X_train)
print(X_train.shape)
print(silhouette_score(X_train, kmeans.labels_))

#Add Cluster Number to each datapoint + save file
df_kmeans=X_train
kmeans_predict_train=kmeans.predict(df_kmeans)
df_kmeans['Cluster Number']=kmeans_predict_train
print(df_kmeans.shape)
print(df_kmeans.head())
export_csv = df_kmeans.to_csv(r'/gdrive/My Drive/CIS 508/Assignment/HW4/KmeansClusters_WCD-8.csv')

#K-Means Clustering ========================================================================
# K=20
kmeans = KMeans(n_clusters=20, init='random', algorithm='elkan')
kmeans.fit(X_train)
kmeans.labels_
print(X_train.shape)
#Print Silhouette measure
print(silhouette_score(X_train, kmeans.labels_))

#Add Cluster Number to each datapoint + save file
df_kmeans=X_train
kmeans_predict_train=kmeans.predict(X_train)

df_kmeans['Cluster Number']=kmeans_predict_train
print(df_kmeans.shape)
print(df_kmeans.head())
export_csv = df_kmeans.to_csv(r'/gdrive/My Drive/CIS 508/Assignment/HW4/KmeansClusters_WCD-20.csv')